behaviors:
  MoveToGoal:
    trainer_type: ppo
    behavioral_cloning:
      demo_path: ./config/rc1.demo
      strength: 0.5
      samples_per_update: 0.2
    hyperparameters:
      batch_size: 2048
      buffer_size: 4096
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 8
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        encoding_size: 256
    max_steps: 2.0e7
    time_horizon: 128
    summary_freq: 10000


